import type { CoreApi } from "@zhiyin/contract";
import type { ConnectionCommands } from "./WorkspaceSurfaces.js";

/** Everything the window can ask the core to do. */
export type WorkspaceCommands = Pick<
  CoreApi,
  | "createTask"
  | "selectTask"
  | "renameTask"
  | "deleteTask"
  | "sendMessage"
  | "keepPaste"
  | "setContextBudget"
  | "setDefaultContextBudget"
  | "setPersonalInstructions"
  | "condenseNow"
  | "openAttachment"
  | "interruptTask"
  | "runningCommands"
  | "commandOutput"
  | "stopCommand"
  | "resolveApproval"
  | "revokeConversationPermission"
  | "resolveUserInput"
  | "setPluginEnabled"
  | "installPlugin"
  | "updatePlugin"
  | "rollbackPlugin"
  | "removePlugin"
  | "createPlugin"
  | "savePluginContents"
  | "editablePluginContents"
  | "setComponentEnabled"
  | "componentContent"
  | "overrideComponent"
  | "resetComponent"
  | "installToolchain"
  | ConnectionCommands
  | "shellAvailability"
  | "recheckShell"
  | "openExternalUrl"
  | "driveBrowser"
  | "chooseWorkspaceView"
  | "showDocument"
  | "closeDocument"
  | "drawDocumentPage"
  | "openDocument"
  | "showDocumentInFolder"
  | "saveProviderApiKey"
  | "clearProviderApiKey"
  | "listModels"
  | "listModelProviders"
  | "selectModel"
  | "configureProfile"
  | "recoverHistory"
  | "chooseWorkspace"
  | "useRecentWorkspace"
  | "previewArtifact"
  | "exportArtifact"
> &
  Partial<
    Pick<
      CoreApi,
      | "frontendReady"
      | "settleSavedConversations"
      | "exportView"
      | "exportConversation"
      | "readPicture"
      | "selectNothing"
      | "dismissIssue"
      | "previewRewind"
      | "commitRewind"
      | "previewUndo"
      | "commitUndo"
      | "compareDocument"
      | "setNotifications"
      | "openDataFolder"
      | "showInFolder"
      | "setAppearance"
      | "setSpelling"
      | "keepPicture"
    >
  >;
